# Generated by Django 5.0.6 on 2025-02-14 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='No description entered')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('location', models.CharField(default='Not specified', max_length=255)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField()),
                ('additional_images', models.ImageField(blank=True, null=True, upload_to='event_details/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='home.event')),
            ],
        ),
    ]
