# Generated by Django 5.0.6 on 2025-02-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_eventbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='charge',
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
