# Generated by Django 5.0.6 on 2025-02-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_event_charge_eventdetails_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
