# Generated by Django 5.0.6 on 2025-02-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_eventdetails_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
