# Generated by Django 5.0.6 on 2025-02-23 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountOffer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_start_date', models.DateField()),
                ('offer_end_date', models.DateField()),
                ('offer_desc', models.CharField(max_length=35)),
                ('discount_percentage', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
    ]
