# Generated by Django 5.0.6 on 2025-02-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_discountoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountoffer',
            name='category',
        ),
    ]
