# Generated by Django 5.0.6 on 2025-02-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_menu_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
    ]
