# Generated by Django 5.0.6 on 2025-03-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_tablebooking_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='booking_time',
            field=models.DateTimeField(),
        ),
    ]
