# Generated by Django 5.0.6 on 2025-03-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_bookingslot_tablebooking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingslot',
            name='slot_time',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
