# Generated by Django 5.0.6 on 2025-03-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_bookingslot_available_tables_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingslot',
            name='time',
        ),
        migrations.AddField(
            model_name='bookingslot',
            name='available_tables',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='bookingslot',
            name='slot_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
