# Generated by Django 5.0.6 on 2025-04-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_userprofile_is_staff_alter_userprofile_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_no',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
