# Generated by Django 5.0.6 on 2025-04-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_order_table_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='Manage_Table',
        ),
    ]
