# Generated by Django 5.0.6 on 2025-04-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_feedback_delete_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
    ]
