# Generated by Django 5.0.6 on 2025-04-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
